/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRidesRouteImport } from './routes/admin.rides'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminGeofencesRouteImport } from './routes/admin.geofences'
import { Route as AdminDuesRouteImport } from './routes/admin.dues'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminApplicantsRouteImport } from './routes/admin.applicants'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppTripsRouteImport } from './routes/_app/trips'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReferralRouteImport } from './routes/_app/referral'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppDriverRouteImport } from './routes/_app/driver'
import { Route as AppBookRouteImport } from './routes/_app/book'
import { Route as AppRideIdRouteImport } from './routes/_app/ride.$id'
import { Route as ApiPublicHooksCheckDuesRouteImport } from './routes/api/public/hooks/check-dues'
import { Route as ApiPublicHooksAdsTickRouteImport } from './routes/api/public/hooks/ads-tick'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidesRoute = AdminRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeofencesRoute = AdminGeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDuesRoute = AdminDuesRouteImport.update({
  id: '/dues',
  path: '/dues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicantsRoute = AdminApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppRideIdRoute = AppRideIdRouteImport.update({
  id: '/ride/$id',
  path: '/ride/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksCheckDuesRoute = ApiPublicHooksCheckDuesRouteImport.update({
  id: '/api/public/hooks/check-dues',
  path: '/api/public/hooks/check-dues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAdsTickRoute = ApiPublicHooksAdsTickRouteImport.update({
  id: '/api/public/hooks/ads-tick',
  path: '/api/public/hooks/ads-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof AppBookRoute
  '/driver': typeof AppDriverRoute
  '/home': typeof AppHomeRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/referral': typeof AppReferralRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/terms': typeof AppTermsRoute
  '/trips': typeof AppTripsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/dues': typeof AdminDuesRoute
  '/admin/geofences': typeof AdminGeofencesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/': typeof AdminIndexRoute
  '/ride/$id': typeof AppRideIdRoute
  '/api/public/hooks/ads-tick': typeof ApiPublicHooksAdsTickRoute
  '/api/public/hooks/check-dues': typeof ApiPublicHooksCheckDuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof AppBookRoute
  '/driver': typeof AppDriverRoute
  '/home': typeof AppHomeRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/referral': typeof AppReferralRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/terms': typeof AppTermsRoute
  '/trips': typeof AppTripsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/dues': typeof AdminDuesRoute
  '/admin/geofences': typeof AdminGeofencesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin': typeof AdminIndexRoute
  '/ride/$id': typeof AppRideIdRoute
  '/api/public/hooks/ads-tick': typeof ApiPublicHooksAdsTickRoute
  '/api/public/hooks/check-dues': typeof ApiPublicHooksCheckDuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/book': typeof AppBookRoute
  '/_app/driver': typeof AppDriverRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/referral': typeof AppReferralRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/trips': typeof AppTripsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/dues': typeof AdminDuesRoute
  '/admin/geofences': typeof AdminGeofencesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/ride/$id': typeof AppRideIdRoute
  '/api/public/hooks/ads-tick': typeof ApiPublicHooksAdsTickRoute
  '/api/public/hooks/check-dues': typeof ApiPublicHooksCheckDuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book'
    | '/driver'
    | '/home'
    | '/privacy'
    | '/profile'
    | '/referral'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trips'
    | '/wallet'
    | '/admin/admins'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/complaints'
    | '/admin/drivers'
    | '/admin/dues'
    | '/admin/geofences'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/rides'
    | '/admin/'
    | '/ride/$id'
    | '/api/public/hooks/ads-tick'
    | '/api/public/hooks/check-dues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/driver'
    | '/home'
    | '/privacy'
    | '/profile'
    | '/referral'
    | '/settings'
    | '/support'
    | '/terms'
    | '/trips'
    | '/wallet'
    | '/admin/admins'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/complaints'
    | '/admin/drivers'
    | '/admin/dues'
    | '/admin/geofences'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/rides'
    | '/admin'
    | '/ride/$id'
    | '/api/public/hooks/ads-tick'
    | '/api/public/hooks/check-dues'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/_app/book'
    | '/_app/driver'
    | '/_app/home'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/referral'
    | '/_app/settings'
    | '/_app/support'
    | '/_app/terms'
    | '/_app/trips'
    | '/_app/wallet'
    | '/admin/admins'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/complaints'
    | '/admin/drivers'
    | '/admin/dues'
    | '/admin/geofences'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/payouts'
    | '/admin/permissions'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/rides'
    | '/admin/'
    | '/_app/ride/$id'
    | '/api/public/hooks/ads-tick'
    | '/api/public/hooks/check-dues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAdsTickRoute: typeof ApiPublicHooksAdsTickRoute
  ApiPublicHooksCheckDuesRoute: typeof ApiPublicHooksCheckDuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rides': {
      id: '/admin/rides'
      path: '/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AdminRidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geofences': {
      id: '/admin/geofences'
      path: '/geofences'
      fullPath: '/admin/geofences'
      preLoaderRoute: typeof AdminGeofencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dues': {
      id: '/admin/dues'
      path: '/dues'
      fullPath: '/admin/dues'
      preLoaderRoute: typeof AdminDuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applicants': {
      id: '/admin/applicants'
      path: '/applicants'
      fullPath: '/admin/applicants'
      preLoaderRoute: typeof AdminApplicantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referral': {
      id: '/_app/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver': {
      id: '/_app/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book': {
      id: '/_app/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ride/$id': {
      id: '/_app/ride/$id'
      path: '/ride/$id'
      fullPath: '/ride/$id'
      preLoaderRoute: typeof AppRideIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/check-dues': {
      id: '/api/public/hooks/check-dues'
      path: '/api/public/hooks/check-dues'
      fullPath: '/api/public/hooks/check-dues'
      preLoaderRoute: typeof ApiPublicHooksCheckDuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ads-tick': {
      id: '/api/public/hooks/ads-tick'
      path: '/api/public/hooks/ads-tick'
      fullPath: '/api/public/hooks/ads-tick'
      preLoaderRoute: typeof ApiPublicHooksAdsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBookRoute: typeof AppBookRoute
  AppDriverRoute: typeof AppDriverRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralRoute: typeof AppReferralRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTermsRoute: typeof AppTermsRoute
  AppTripsRoute: typeof AppTripsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppRideIdRoute: typeof AppRideIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookRoute: AppBookRoute,
  AppDriverRoute: AppDriverRoute,
  AppHomeRoute: AppHomeRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralRoute: AppReferralRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTermsRoute: AppTermsRoute,
  AppTripsRoute: AppTripsRoute,
  AppWalletRoute: AppWalletRoute,
  AppRideIdRoute: AppRideIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicantsRoute: typeof AdminApplicantsRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminDuesRoute: typeof AdminDuesRoute
  AdminGeofencesRoute: typeof AdminGeofencesRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminRidesRoute: typeof AdminRidesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicantsRoute: AdminApplicantsRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminDuesRoute: AdminDuesRoute,
  AdminGeofencesRoute: AdminGeofencesRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminRidesRoute: AdminRidesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAdsTickRoute: ApiPublicHooksAdsTickRoute,
  ApiPublicHooksCheckDuesRoute: ApiPublicHooksCheckDuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
